openapi: 3.0.0
info:
  title: MEG19008 Middleware API
  description: MEG19008 Middleware API
  version: 0.0.1
servers:
- url: http://localhost:8080/
tags:
- name: scenarioTemplate
  description: Scenario templates
- name: DIM, NUM constraints
  description: DIM and NUM constraints
- name: userScenario
  description: User scenarios
- name: optimizations
  description: optimizations list
paths:
  /scenarioTemplate:
    get:
      tags:
      - scenarioTemplate
      summary: Returns a collection of the scenario templates
      operationId: getScenarioTemplates
      parameters:
      - name: filterQuery
        in: query
        description: |
          Basic filtering criteria in exploded form. See [Basic Filtering](https://developer.sas.com/apis/rest/Topics/#basic-filtering)
        required: false
        style: form
        explode: true
        schema:
          type: string
          additionalProperties:
            type: string
      - name: filter
        in: query
        description: |
          Filter criteria for selecting objects to return. See [Filtering in SAS Viya REST APIs](https://developer.sas.com/apis/rest/Topics/#filters)
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: sortBy
        in: query
        description: Sort criteria for the collection
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: start
        in: query
        description: Offset of the first object to return. Defaults to 0.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: limit
        in: query
        description: Maximum number of objecs to return. Defaults to 10.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: A collection of templates.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scenarioTemplateCollection'
      x-swagger-router-controller: ScenarioTemplate
    post:
      tags:
      - scenarioTemplate
      summary: Creates a new scenario template
      operationId: createScenarioTemplate
      requestBody:
        description: The new scenario template
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scenarioTemplateCreate'
        required: true
      responses:
        "201":
          description: The scenario template created
          headers:
            Location:
              description: The URI of the newly created scenario template.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scenarioTemplate'
      x-swagger-router-controller: ScenarioTemplate
  /scenarioTemplate/{scenarioTemplateCd}:
    delete:
      tags:
      - scenarioTemplate
      summary: Delete selected scenario template
      operationId: scenarioTemplateScenarioTemplateCdDELETE
      parameters:
      - name: scenarioTemplateCd
        in: path
        description: The code of the deleting scenario
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: If-Match
        in: header
        description: The entity tag obtained from the most recent ETag response header.
          It must match the current entity tag.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: If-Unmodified-Since
        in: header
        description: The value of the lastModified date of the object. If the object
          has been updated since this time, the update fails.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Removed scenario template
      x-swagger-router-controller: ScenarioTemplate
    patch:
      tags:
      - scenarioTemplate
      summary: Make a partial update of a scenario template
      description: |
        Updates the provided fields of a scenario template. The client can provide a sparsely populated object, and only the non-null fields contribute to the updates. A body such as { "name": "NewScenarioTemplateName" } causes the scenario template to have its name changed, but no other field is affected. The full resulting object is returned in the response.
      operationId: patchScenarioTemplate
      parameters:
      - name: scenarioTemplateCd
        in: path
        description: The code of the updatable scenario template
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: If-Match
        in: header
        description: The entity tag obtained from the most recent ETag response header.
          It must match the current entity tag.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: If-Unmodified-Since
        in: header
        description: The value of the lastModified date of the object. If the object
          has been updated since this time, the update fails.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: The scenario template to patch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scenarioTemplatePatch'
        required: true
      responses:
        "200":
          description: The patched scenario template
          headers:
            Last-Modified:
              $ref: '#/components/headers/Last-Modified'
            Etag:
              $ref: '#/components/headers/Etag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scenarioTemplate'
      x-swagger-router-controller: ScenarioTemplate
  /dimConstraints:
    get:
      tags:
      - DIM, NUM constraints
      summary: Returns a collection of DIM constraints
      operationId: getDimConstraints
      responses:
        "200":
          description: A collection of DIM constraints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dimConstraints'
      x-swagger-router-controller: DIMNUMConstraints
  /numConstraint:
    get:
      tags:
      - DIM, NUM constraints
      summary: Returns a collection of NUM constraints
      operationId: getNumConstraints
      responses:
        "200":
          description: A collection of NUM constraints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/numConstraints'
      x-swagger-router-controller: DIMNUMConstraints
  /userScenarios:
    get:
      tags:
      - userScenario
      summary: Returns a collections of the user scenarios
      operationId: getUserScenarios
      responses:
        "200":
          description: A collections of user scenarios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userScenariosCollections'
      x-swagger-router-controller: UserScenario
    post:
      tags:
      - userScenario
      summary: Posts  user scenario
      operationId: postUserScenario
      responses:
        "201":
          description: User scenario posted
          headers:
            Location:
              description: The URI of the newly created scenario template.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userScenarioCreate'
      x-swagger-router-controller: UserScenario
    delete:
      tags:
      - userScenario
      summary: Deletes user scenario
      operationId: deleteUserScenario
      responses:
        "200":
          description: Removed scenario template
      x-swagger-router-controller: UserScenario
    patch:
      tags:
      - userScenario
      summary: Updates user scenarion and specify constraints
      operationId: patchUserScenario
      responses:
        "200":
          description: The patched user scenario
          headers:
            Last-Modified:
              $ref: '#/components/headers/Last-Modified'
            Etag:
              $ref: '#/components/headers/Etag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userScenario'
      x-swagger-router-controller: UserScenario
components:
  schemas:
    baseCollection:
      properties:
        start:
          type: integer
          description: The zero-based index of the first item in the collection.
        limit:
          type: integer
          description: The number of items that were requested for the collection.
        count:
          type: integer
          description: The number of items in the collection.
      description: |
        This is a base schema used to define paginated collections of resources. This base schema is extended by other schemas in APIs by adding an 'items' array property.
    scenarioTemplateCollection:
      description: A collection of scenario templates
      allOf:
      - $ref: '#/components/schemas/baseCollection'
      - type: object
        properties:
          items:
            type: array
            description: An array consisting of scenario templates.
            items:
              $ref: '#/components/schemas/scenarioTemplate'
    scenarioTemplatePatch:
      properties:
        PATH:
          type: string
          description: The path to the file
        TARGET_ATTR_LABEL:
          type: string
          description: The used target function
        TEXT_COMMENT:
          type: string
          description: The comment to the scenario template
        SCT_CONSTRAINT_DIM_PARAMS:
          minLength: 1
          type: array
          description: An array consisting of the scenario template constraint params
          items:
            $ref: '#/components/schemas/scenarioTemplateConstraintDimParam'
        SCT_CONSTRAINT_NUM_PARAMS:
          minLength: 1
          type: array
          description: An array consisting of scenario template constraint params
          items:
            $ref: '#/components/schemas/scenarioTemplateConstraintNumParam'
      description: The scenario template to be patched
    scenarioTemplateCreate:
      required:
      - NAME
      - PATH
      - SCT_CONSTRAINT_DIM_PARAMS
      - SCT_CONSTRAINT_NUM_PARAMS
      - TARGET_ATTR_LABEL
      description: The new scenario template
      allOf:
      - $ref: '#/components/schemas/scenarioTemplatePatch'
      - type: object
        properties:
          NAME:
            type: string
            description: The name of the scenario template
    scenarioTemplate:
      description: The full representation of the scenario template
      allOf:
      - $ref: '#/components/schemas/scenarioTemplateCreate'
      - type: object
        properties:
          SCENARIO_TEMPLATE_CD:
            type: string
            description: The code of the scenario template
          USER_CREATED:
            type: string
            description: The user created the scenario template
          DTTM_CREATED:
            type: string
            description: The date and time the scenario template was created
            format: date-time
          USER_UPDATED:
            type: string
            description: The user updated the scenario template
          DTTM_UPDATED:
            type: string
            description: The date and time the scenario template was updated
            format: date-time
    scenarioTemplateConstraintDimParam:
      example:
        ATTR_NAME: CPCHANNEL_CD+OFFER_ID
        ATTR_LABEL: Канал+Предложение
        DIM_TABLE_NAME: CON_CH_OF_UC
      allOf:
      - $ref: '#/components/schemas/scenarioTemplateConstraintParam'
      - required:
        - DIM_TABLE_NAME
        type: object
        properties:
          DIM_TABLE_NAME:
            type: string
            description: The short name of the optimizator table
    scenarioTemplateConstraintNumParam:
      example:
        ATTR_NAME: CONV
        ATTR_LABEL: Конверсия
      allOf:
      - $ref: '#/components/schemas/scenarioTemplateConstraintParam'
    scenarioTemplateConstraintParam:
      required:
      - ATTR_LABEL
      - ATTR_NAME
      properties:
        ATTR_NAME:
          type: string
          description: |
            The name of the attribute of the constraint param.
        ATTR_LABEL:
          type: string
          description: The label of the attribute of the constraint param
      description: A scenario template constraint param
    userScenariosCollections:
      properties:
        SCENARIO_CD:
          type: string
          description: user scenario code
        NAME_SCN:
          type: string
          description: user scenario name
        NAME_SCT:
          type: string
          description: scenario template name
        TEXT_COMMENT:
          type: string
          description: user scenario comment
        USER_UPDATED:
          type: string
          description: user name who updated scenario last
        DTTM_UPDATED:
          type: string
          description: datetime of last edition
        DTIME_LAST_OPTIMIZATION:
          type: string
          description: datetime of last optimization start
      description: user scenarios collection
      example:
        NAME_SCN: NAME_SCN
        SCENARIO_CD: SCENARIO_CD
        DTIME_LAST_OPTIMIZATION: DTIME_LAST_OPTIMIZATION
        USER_UPDATED: USER_UPDATED
        NAME_SCT: NAME_SCT
        DTTM_UPDATED: DTTM_UPDATED
        TEXT_COMMENT: TEXT_COMMENT
    userScenarioCreate:
      required:
      - NAME_SCN
      - NAME_SCT
      properties:
        NAME_SCN:
          type: string
          description: User scenario name
        NAME_SCT:
          type: string
          description: Scenario template name attached to user scenario
        TEXT_COMMENT:
          type: string
          description: User scenario text comment
      description: The new user scenario
      example:
        NAME_SCN: NAME_SCN
        NAME_SCT: NAME_SCT
        TEXT_COMMENT: TEXT_COMMENT
    userScenario:
      required:
      - NAME_SCN
      - NAME_SCT
      properties:
        NAME_SCN:
          type: string
          description: User scenario name
        NAME_SCT:
          type: string
          description: Scenario template name attached to user scenario
        TEXT_COMMENT:
          type: string
          description: User scenario text comment
      description: The new user scenario
      example:
        NAME_SCN: NAME_SCN
        NAME_SCT: NAME_SCT
        TEXT_COMMENT: TEXT_COMMENT
    dimConstraints:
      properties:
        constraints:
          type: array
          description: An array consisting of scenario templates.
          items:
            $ref: '#/components/schemas/dimConstraints_constraints'
      description: List of DIM constraints
      example:
        constraints:
        - DIM_TABLE_NAME: DIM_TABLE_NAME
          ATTR_NAME: ATTR_NAME
          ATTR_LABEL: ATTR_LABEL
        - DIM_TABLE_NAME: DIM_TABLE_NAME
          ATTR_NAME: ATTR_NAME
          ATTR_LABEL: ATTR_LABEL
    numConstraints:
      properties:
        constraints:
          type: array
          description: An array consisting of scenario templates.
          items:
            $ref: '#/components/schemas/numConstraints_constraints'
      description: List of NUM constraints
      example:
        constraints:
        - ATTR_NAME: ATTR_NAME
          ATTR_LABEL: ATTR_LABEL
        - ATTR_NAME: ATTR_NAME
          ATTR_LABEL: ATTR_LABEL
    dimConstraints_constraints:
      properties:
        ATTR_NAME:
          type: string
          description: Attribute name of the constraint
        ATTR_LABEL:
          type: string
          description: Attribute label of the constraint
        DIM_TABLE_NAME:
          type: string
          description: Name of dim table
      example:
        DIM_TABLE_NAME: DIM_TABLE_NAME
        ATTR_NAME: ATTR_NAME
        ATTR_LABEL: ATTR_LABEL
    numConstraints_constraints:
      properties:
        ATTR_NAME:
          type: string
          description: Attribute name of the constraint
        ATTR_LABEL:
          type: string
          description: Attribute label of the constraint
      example:
        ATTR_NAME: ATTR_NAME
        ATTR_LABEL: ATTR_LABEL
  parameters:
    ifMatch:
      name: If-Match
      in: header
      description: The entity tag obtained from the most recent ETag response header.
        It must match the current entity tag.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ifUnmodifiedSince:
      name: If-Unmodified-Since
      in: header
      description: The value of the lastModified date of the object. If the object
        has been updated since this time, the update fails.
      required: false
      style: simple
      explode: false
      schema:
        type: string
    start:
      name: start
      in: query
      description: Offset of the first object to return. Defaults to 0.
      required: false
      style: form
      explode: true
      schema:
        type: integer
    limit:
      name: limit
      in: query
      description: Maximum number of objecs to return. Defaults to 10.
      required: false
      style: form
      explode: true
      schema:
        type: integer
    filterQuery:
      name: filterQuery
      in: query
      description: |
        Basic filtering criteria in exploded form. See [Basic Filtering](https://developer.sas.com/apis/rest/Topics/#basic-filtering)
      required: false
      style: form
      explode: true
      schema:
        type: object
        additionalProperties:
          type: string
    filter:
      name: filter
      in: query
      description: |
        Filter criteria for selecting objects to return. See [Filtering in SAS Viya REST APIs](https://developer.sas.com/apis/rest/Topics/#filters)
      required: false
      style: form
      explode: true
      schema:
        type: string
    sortBy:
      name: sortBy
      in: query
      description: Sort criteria for the collection
      required: false
      style: form
      explode: true
      schema:
        type: string
  headers:
    Etag:
      description: A tag that identifies this revision of this object.
      style: simple
      explode: false
      schema:
        type: string
    Last-Modified:
      description: The RFC 1123 date string representing the timestamp of the last
        update to this object.
      style: simple
      explode: false
      schema:
        type: string
